### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rhpluss**
fixed one spelling and added one more line of request

### CODE REVIEW

**Review by maccaronibud — CHANGES_REQUESTED** [review]
please do better next time

**Comment by rhpluss** [comment]
monster maccaron !!!

**Comment by rhpluss** [comment]
why do not you accept that people can improve your work further?

**Comment by maccaronibud** [comment]
> monster maccaron !!!

spell my name correctly mister, or should i say, buddy...

**Comment by rhpluss** [comment]
stop chatting and accept my changes right now>>>>

**Comment by maccaronibud** [comment]
> stop chatting and accept my changes right now>>>>

ok fine

**Review by maccaronibud — APPROVED** [review]

**Pull request merged**
